"""Add gold column to parts_inventory

Revision ID: 12058c9fceaa
Revises: 
Create Date: 2024-07-29 08:52:40.787794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12058c9fceaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partsinout')
    with op.batch_alter_table('parts__inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts__inventory', schema=None) as batch_op:
        batch_op.drop_column('gold')

    op.create_table('partsinout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=80), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=False),
    sa.Column('usage', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    # ### end Alembic commands ###
